### ISSUE TITLE
Expose VZLinux 8 as RHEL/Centos - possible?

### ISSUE THREAD

**Issue by futureweb** [vzlinux/docs#1]
I think I can remember reading somewhere that VZLinux should have the functionality to expose itself als RHEL/CENTOS to software running in it ... but unfortunately I can't find any information about it in the Docs. Am I wrong here?

Cause: MARIADB installer refused the automated installation because it doesn't know "VZLinux" ... Is it possible to set VZLinux so that it exposes itself as RHEL or CENTOS 8?

thx
Andy

**Comment by Cormacus** [comment]
Hi,

There is indeed a way to do this. I updated the documentation. See https://github.com/vzlinux/docs#masking-virtuozzo-linux-as-centos-or-redhat-enterprise-linux.

Thanks for the suggestion!
